project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning Blog"
  repo-url: https://github.com/kboodlal/Machine-Learning-Blog
  repo-branch: "master"
  repo-actions: [source]
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

